#!/bin/bash

echo "Pushing Lithos project to GitHub..."
echo ""
echo "This script will help you push the code to your GitHub repository."
echo ""
echo "Option 1: Using GitHub CLI (recommended)"
echo "If you have GitHub CLI installed, run:"
echo "  gh auth login"
echo "  git push -u origin main"
echo ""
echo "Option 2: Using HTTPS with PAT"
echo "Run the following command and enter your PAT when prompted for password:"
echo "  git push -u https://github.com/anishkganesh/Lithos.git main"
echo ""
echo "Option 3: Using SSH"
echo "If you have SSH keys set up, run:"
echo "  git remote set-url origin git@github.com:anishkganesh/Lithos.git"
echo "  git push -u origin main"
echo ""
echo "Your repository URL: https://github.com/anishkganesh/Lithos"
echo ""
echo "Note: Make sure your PAT has 'repo' scope permissions." 